import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/Utills/Providers";
import Nav from "@/Components/Nav";
import { Box } from "@chakra-ui/react";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Providers>
          <Box fontFamily="body">
            <Nav />
            {children}
            <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  );
}
